#! /bin/sh

set -eu


SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source "$SCRIPT_DIR/venv/bin/activate"

PYTHONPATH="$SCRIPT_DIR" python3 "$SCRIPT_DIR/yandex_disk_rsync" "$@"

